### ISSUE TITLE
Message to control HV-accumulator fans during charging

### ISSUE THREAD

**Issue by mattebit** [eagletrt/can#11]
It could be useful to have a can message to ask the pork to increase the fan speed during charging.
The devices are: from HANDCART to BMS-HV
An int with the speed from 0-100 should be enough.

I think an ack message is not necessary

**Comment by fedebone00** [comment]
The pork is now self adjusting fans based on temps, is this still needed?

**Comment by mattebit** [comment]
maybe?

**Comment by fedebone00** [comment]
done: [commit](https://github.com/eagletrt/can/commit/0cea4c3eb2af03702b105a55ad97a3aa2544ffb9)
